import os
import tempfile
from datetime import datetime
from reportlab.lib.pagesizes import letter
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.units import inch
from reportlab.lib import colors
from reportlab.lib.enums import TA_LEFT, TA_CENTER
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, HRFlowable
from docx import Document
from docx.shared import Pt, RGBColor, Inches
from docx.enum.text import WD_ALIGN_PARAGRAPH
from docx.oxml.ns import qn
from docx.oxml import OxmlElement

NAVY = colors.HexColor("#0A1628")
TEAL = colors.HexColor("#0EA5E9")
LIGHT_GREY = colors.HexColor("#F1F5F9")
MID_GREY = colors.HexColor("#64748B")
BLACK = colors.HexColor("#0F172A")


def export_pdf(sections: list) -> str:
    tmp = tempfile.NamedTemporaryFile(delete=False, suffix=".pdf")
    path = tmp.name
    tmp.close()

    doc = SimpleDocTemplate(
        path, pagesize=letter,
        rightMargin=inch, leftMargin=inch,
        topMargin=inch, bottomMargin=inch,
    )

    title_style = ParagraphStyle("Title", fontName="Helvetica-Bold", fontSize=18,
                                  textColor=NAVY, alignment=TA_CENTER, spaceAfter=4)
    subtitle_style = ParagraphStyle("Subtitle", fontName="Helvetica", fontSize=10,
                                     textColor=MID_GREY, alignment=TA_CENTER, spaceAfter=16)
    section_style = ParagraphStyle("Section", fontName="Helvetica-Bold", fontSize=11,
                                    textColor=TEAL, spaceBefore=14, spaceAfter=4)
    body_style = ParagraphStyle("Body", fontName="Helvetica", fontSize=10,
                                 textColor=BLACK, leading=16, spaceAfter=4)
    bullet_style = ParagraphStyle("Bullet", fontName="Helvetica", fontSize=10,
                                   textColor=BLACK, leading=16, leftIndent=16, spaceAfter=2)

    story = []
    story.append(Paragraph("CLINICAL CONSULTATION NOTE", title_style))
    story.append(Paragraph(f"Generated: {datetime.now().strftime('%B %d, %Y — %H:%M')}", subtitle_style))
    story.append(HRFlowable(width="100%", thickness=1.5, color=TEAL, spaceAfter=8))

    for section in sections:
        title = section.get("title", "")
        content = section.get("content", "")
        stype = section.get("type", "text")

        story.append(Paragraph(title.upper(), section_style))
        story.append(HRFlowable(width="100%", thickness=0.5, color=LIGHT_GREY, spaceAfter=6))

        if stype == "list" and content:
            for line in content.split("\n"):
                line = line.strip()
                if line:
                    story.append(Paragraph(f"• {line}", bullet_style))
        elif content:
            story.append(Paragraph(str(content), body_style))
        else:
            story.append(Paragraph("Not recorded.", body_style))

    story.append(Spacer(1, 20))
    story.append(HRFlowable(width="100%", thickness=1, color=NAVY, spaceAfter=6))
    story.append(Paragraph(
        "This document was generated by Clinical Scribe and must be reviewed and signed by the treating physician.",
        ParagraphStyle("Footer", fontName="Helvetica-Oblique", fontSize=8,
                       textColor=MID_GREY, alignment=TA_CENTER),
    ))

    doc.build(story)
    return path


def export_docx(sections: list) -> str:
    doc = Document()

    for section_obj in doc.sections:
        section_obj.top_margin = Inches(1)
        section_obj.bottom_margin = Inches(1)
        section_obj.left_margin = Inches(1)
        section_obj.right_margin = Inches(1)

    style = doc.styles["Normal"]
    style.font.name = "Arial"
    style.font.size = Pt(11)

    def set_heading(para, text: str, size: int = 12, color_hex: str = "0EA5E9") -> None:
        run = para.add_run(text)
        run.bold = True
        run.font.size = Pt(size)
        run.font.color.rgb = RGBColor(
            int(color_hex[0:2], 16), int(color_hex[2:4], 16), int(color_hex[4:6], 16)
        )

    def add_divider(bold: bool = False) -> None:
        p = doc.add_paragraph()
        p.paragraph_format.space_before = Pt(0)
        p.paragraph_format.space_after = Pt(2)
        pPr = p._p.get_or_add_pPr()
        pBdr = OxmlElement("w:pBdr")
        bottom = OxmlElement("w:bottom")
        bottom.set(qn("w:val"), "single")
        bottom.set(qn("w:sz"), "6" if bold else "4")
        bottom.set(qn("w:space"), "1")
        bottom.set(qn("w:color"), "0A1628" if bold else "CBD5E1")
        pBdr.append(bottom)
        pPr.append(pBdr)

    title = doc.add_paragraph()
    title.alignment = WD_ALIGN_PARAGRAPH.CENTER
    title.paragraph_format.space_after = Pt(2)
    set_heading(title, "CLINICAL CONSULTATION NOTE", size=18, color_hex="0A1628")

    sub = doc.add_paragraph()
    sub.alignment = WD_ALIGN_PARAGRAPH.CENTER
    sub.paragraph_format.space_after = Pt(8)
    run = sub.add_run(f"Generated: {datetime.now().strftime('%B %d, %Y — %H:%M')}")
    run.font.size = Pt(9)
    run.font.color.rgb = RGBColor(0x64, 0x74, 0x8B)
    run.italic = True

    add_divider(bold=True)

    for section in sections:
        title_text = section.get("title", "")
        content = section.get("content", "")
        stype = section.get("type", "text")

        h = doc.add_paragraph()
        h.paragraph_format.space_before = Pt(10)
        h.paragraph_format.space_after = Pt(2)
        set_heading(h, title_text.upper())
        add_divider()

        if stype == "list" and content:
            for line in content.split("\n"):
                line = line.strip()
                if line:
                    p = doc.add_paragraph(style="List Bullet")
                    p.paragraph_format.space_after = Pt(1)
                    p.add_run(line).font.size = Pt(10)
        elif content:
            p = doc.add_paragraph()
            p.paragraph_format.space_after = Pt(4)
            p.add_run(str(content)).font.size = Pt(10)
        else:
            p = doc.add_paragraph()
            p.add_run("Not recorded.").font.size = Pt(10)

    doc.add_paragraph()
    add_divider(bold=True)
    footer_p = doc.add_paragraph()
    footer_p.alignment = WD_ALIGN_PARAGRAPH.CENTER
    footer_run = footer_p.add_run(
        "This document was generated by Clinical Scribe and must be reviewed and signed by the treating physician."
    )
    footer_run.italic = True
    footer_run.font.size = Pt(8)
    footer_run.font.color.rgb = RGBColor(0x94, 0xA3, 0xB8)

    tmp = tempfile.NamedTemporaryFile(delete=False, suffix=".docx")
    path = tmp.name
    tmp.close()
    doc.save(path)
    return path
